name: Test Stylesheet

on:
  push:
    branches:
      - main
    paths:
      - '**.xsl'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run Test
        run: bash tests/test.sh